Jk admin view
Konrad123456/megak-head-hunter-fe pull request #13
Opened 2023-04-21 17:21 UTC by JarekKrolik

task 1  [MKHH-#32] Stworzenia formularza dodawania HR w widoku admina [FE]
tast 2 [MKHH-#15] Widok Admina -- Projekt layoutu strony [FE]

2023-04-22 19:52 UTC, Alendart commented on src/components/Formik/Forms/AdminViewFormHrAdd.tsx
> +                   .min(3,"Nazwa firmy musi mieć minimum 4 znaki"),
Piszesz o 4 znakach a w yupie wskazałeś 3 jako minimum

2023-04-22 19:56 UTC, Alendart commented on src/components/Formik/Forms/AdminViewFormHrAdd.tsx
> +               <button className={'btn'} type="submit">wyślij</button>
Dodając formularz do logowania stworzyłem reużywalny komponent SubmitBtn w którym podaje się tylko text do wyświetlenia. Możesz od razu go tutaj zastosować - Przy każdym formularzu taki przycisk będzie potrzebny

2023-04-22 20:03 UTC, Alendart commented on src/components/Formik/Forms/AdminViewFormStudentsAdd.tsx
Przesyłanie plików w Reactie wymaga odwołania się do Hooka useRef który będzie przechowywał listę plików w momencie kiedy użytkownik poda jakiś plik. 

useRef.current - tutaj będzie tablica plików a w samym formiku zapisze się tylko "udawana" ścieżka do pliku z którą nie da się nic zrobić

2023-04-22 20:05 UTC, Alendart commented on src/components/Formik/Forms/AdminViewPasswordChangeForm.tsx
> +        <p>powtórz hasło</p>
Nie masz miejsca na drugą wartość w formiku - input passwordCheck zostanie nieobsłużony i nic się z nim nie da zrobić

2023-04-22 20:10 UTC, Alendart requested changes
Wbiłem komentarze w konkretnych miejscach ale na przyszłość robienie formularza musi być na osobnym branchu do widoku bo spokojnie widok moglibyśmy już zmergować :)

2023-04-23 17:07 UTC, JarekKrolik commented on src/components/Formik/Forms/AdminViewFormHrAdd.tsx
> +                   .min(3,"Nazwa firmy musi mieć minimum 4 znaki"),
poprawione

2023-04-23 17:09 UTC, JarekKrolik commented on src/components/Formik/Forms/AdminViewFormHrAdd.tsx
> +               <button className={'btn'} type="submit">wyślij</button>
na tą chwilę zostawiłem zwykłe buttony, jak dodaję ten komponent Button formularze nie wysyłają się, może po mergu się podmieni

2023-04-23 17:09 UTC, JarekKrolik commented on src/components/Formik/Forms/AdminViewPasswordChangeForm.tsx
> +        <p>powtórz hasło</p>
poprawione

2023-04-23 17:09 UTC, JarekKrolik commented on src/components/Formik/Forms/AdminViewFormStudentsAdd.tsx
poprawione

2023-04-24 19:50 UTC, Alendart commented on src/components/Formik/Forms/AdminViewPasswordChangeForm.tsx
> +                        .matches(/[@$!%*#?&]+/, "Jeden znak specjalny"),
Messeges which you write in Yup are displayed to client on front - Right now they don't inform client properly about details of problem

For example - rename "Jeden duży znak" na "Hasło musi zawierać jeden duży znak" 

On the other hand - i think that best will be to combine it into one RegEx and display one message to client " Hasło musi zawierać minimum jedną dużą literę, jedną cyfrę i jeden znak specjalny"

2023-04-24 19:52 UTC, Alendart requested changes
Change Yup messages in AdminViewPasswordChangeForm and we will be done :)

2023-04-25 20:19 UTC, Alendart approved these changes
All fine now

2023-04-26 05:06 UTC, Konrad123456 approved these changes

2023-04-26 05:11 UTC, merged